TaskManagentHONB2/Models/ErrorViewModel.cs
namespace TaskManagentHONB2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TaskManagentHONB2/Models/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace TaskManagentHONB2.Models
{
    public class LoginModel
    {
        [Required]
        public string? Email { get; set; }

        [Required]
        public string? Password { get; set; }
    }
}

TaskManagentHONB2/Models/StatusModel.cs
namespace TaskManagentHONB2.Models
{
    public class StatusModel
    {
        public string? Status { get; set; }
    }
}

TaskManagentHONB2/Models/User.cs
using DAL.Models;
using System.ComponentModel.DataAnnotations;

namespace TaskManagentHONB2.Models
{
    public class User
    {
        [Key]
        public int UserId { get; set; }

        [Required]
        public string? Username { get; set; }

        [Required]
        public string? Password { get; set; }

        [Required]
        [EmailAddress]
        public string? Email { get; set; }
        public List<UsersTask>? Tasks { get; set; }
    }
}

TaskManagentHONB2/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TaskManagentHONB2.Models;

namespace TaskManagentHONB2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TaskManagentHONB2/Controllers/TaskingController.cs
using DAL.Interfaces;
using DAL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TaskManagentHONB2.Models;

namespace TaskManagentHONB2.Controllers
{
    public class TaskingController : Controller
    {
        public readonly ITask _task;
        public readonly IUsers _user;
        public TaskingController(ITask task, IUsers user)
        {
            _task = task;
            _user = user;
        }


        [HttpGet]
        public async Task<IActionResult> AddTask()
        {
            //on load get list of users from db and send to viewbag
            ViewBag.userlist = new SelectList(await _user.GetAllUsers(), "UserId", "Username"); // getting id ,username ,email , password
            //                                              from all Users data , Userid and username , username id for UI and Userid is for backend    
            return View();
        }


        [HttpPost, ActionName("AddTask")]
        public IActionResult Ajhjhgjgj(UsersTask obj)
        {
            if (ModelState.IsValid)
            {
                _task.CreateTask(obj);
                return RedirectToAction("TaskList");
            }
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> TaskList()
        {
            var tasks = await _task.GetAllTasks();
            return View(tasks);
        }

        [HttpGet]
        public async Task<IActionResult> GetTaskByStatus()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetTaskByStatus(StatusModel obj)
        {
            //  string Status = Request.Form["status"].ToString();
            ViewBag.res = _task.GetAllTasksByStatus(obj.Status);
            return View();
        }
    }
}

TaskManagentHONB2/Controllers/UserOpsController.cs
using DAL.Interfaces;
using DAL.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TaskManagentHONB2.Models;

namespace TaskManagentHONB2.Controllers
{
    public class UserOpsController : Controller
    {
        public readonly IUsers _iuser;
        public UserOpsController(IUsers iuser)
        {
            _iuser = iuser;
        }


        [HttpGet]
        public IActionResult AddUser()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddUser(TaskManagentHONB2.Models.User obj)
        {
            DAL.Models.User user = new DAL.Models.User()
            {
                Username = obj.Username,  // lhs is DAL.Models.User, rhs is TaskManagentHONB2.Models.User
                Password = obj.Password,
                Email = obj.Email
            };
            if (obj == null)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {

                await _iuser.CreateUser(user);
                return RedirectToAction("Login");
            }
            return View();
        }


        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Login(LoginModel obj)
        {
            if (obj == null)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                bool isValidUser = _iuser.ValidateUser(obj.Email, obj.Password);
                int myusers = await _iuser.GetUserIDByEmail(obj.Email);  // user id ,6
                if (obj.Email == "admin@yahoo.com" && obj.Password == "admin")
                {
                    return RedirectToAction("AdminHomePage");
                }
                else
                {
                    if (isValidUser)
                    {
                        HttpContext.Session.SetInt32("UserID", myusers);


                        return RedirectToAction("UserHomePage");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    }
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult UserHomePage()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AdminHomePage()
        {
            return View();
        }

        public IActionResult Logout()
        {
            return RedirectToAction("Login");
        }

        public async Task<IActionResult> TaskList()
        {
            int? AssignedUserId = HttpContext.Session.GetInt32("UserID");
            if (AssignedUserId == null)
            {
                return View();
            }
            var users = await _iuser.GetAllUsersTaskByID(AssignedUserId.Value);
            return View(users);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateStatus(int TaskId)
        {
            return View(await _iuser.GetTaskByTaskID(TaskId));
        }

        [HttpPost]
        public async Task<IActionResult> UpdateStatus(UsersTask obj)
        {
            await _iuser.UpdateStatusAsync(obj.TaskId, obj.Status);
            return RedirectToAction("TaskList");
        }

    }
}

TaskManagentHONB2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TaskManagentHONB2/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagentHONB2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagentHONB2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskManagentHONB2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasking" asp-action="AddTask">Add Task</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasking" asp-action="TaskList">View Task</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasking" asp-action="GetTaskByStatus">Search Task</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Userops" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - TaskManagentHONB2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskManagentHONB2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagentHONB2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagentHONB2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskManagentHONB2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - TaskManagentHONB2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskManagentHONB2/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagentHONB2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagentHONB2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskManagentHONB2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="userops" asp-action="TaskList">View Task</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Userops" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - TaskManagentHONB2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskManagentHONB2/Views/Tasking/AddTask.cshtml
@model DAL.Models.UsersTask

@{
    ViewData["Title"] = "AddTask";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>AddTask</h1>

<h4>UsersTask</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddTask">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>

                <select asp-for="Status" class="form-control">
                    <option value="">-- Select Status --</option>
                    <option value="Assigned">Assigned</option>
                    <option value="Pending">Pending</option>
                    <option value="In Progress">In Progress</option>
                    <option value="Completed">Completed</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssignedUserId" class="control-label"></label>
                <select asp-for="AssignedUserId" class="form-control" asp-items="ViewBag.userlist">
                    <option value="">-- Select User --</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TaskManagentHONB2/Views/Tasking/GetTaskByStatus.cshtml
@model TaskManagentHONB2.Models.StatusModel


@{
    ViewData["Title"] = "GetTaskByStatus";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>GetTaskByStatus</h1>


<form method="post">
    <select  asp-for="Status">
        <option value="">-- Select Status --</option>
        <option value="Assigned">Assigned</option>
        <option value="Pending">Pending</option>
        <option value="In Progress">In Progress</option>
        <option value="Completed">Completed</option>
    </select>

    <input type="submit" name="submit" value="submit" />
</form>



    <table class="table">
        <thead>
            <tr>
                <th>
                    Title
                </th>
                <th>
                    Description
                </th>
                <th>
                    DueDate
                </th>
                <th>
                    Status
                </th>
                <th>
                    AssignedUser
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.res)
            {
                <tr>
                    <td>
                        @item.Title
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        @item.DueDate
                    </td>
                    <td>
                        @item.Status
                    </td>
                    <td>
                        @item.AssignedUser.Username
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.TaskId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.TaskId">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.TaskId">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

TaskManagentHONB2/Views/Tasking/TaskList.cshtml
@model IEnumerable<DAL.Models.UsersTask>

@{
    ViewData["Title"] = "TaskList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>TaskList</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssignedUser)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssignedUser.Username)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TaskId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TaskId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TaskId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

TaskManagentHONB2/Views/UserOps/AddUser.cshtml
@model TaskManagentHONB2.Models.User

@{
    ViewData["Title"] = "AddUser";
}

<h1>AddUser</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Login">Back to Login</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskManagentHONB2/Views/UserOps/AdminHomePage.cshtml
@{
    ViewData["Title"] = "AdminHomePage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>AdminHomePage</h1>

TaskManagentHONB2/Views/UserOps/Login.cshtml
@model TaskManagentHONB2.Models.LoginModel

@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Adduser">Create Account</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskManagentHONB2/Views/UserOps/TaskList.cshtml
@model IEnumerable<DAL.Models.UsersTask>

@{
    ViewData["Title"] = "TaskList";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h1>TaskList</h1>
<style>

    .disabled-link {
        pointer-events: none;
        color: gray;
        text-decoration: none;
        cursor: not-allowed;
    }</style>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DueDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>



                <td>
                    <a asp-action="UpdateStatus"
                       asp-route-TaskId="@item.TaskId"
                       class="@(item.Status == "Completed" ? "disabled-link" : "")">
                        Edit
                    </a>|
                   
                    <a asp-action="Details" asp-route-id="@item.TaskId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.TaskId">Delete</a>
                </td>

            </tr>
        }
    </tbody>
</table>

TaskManagentHONB2/Views/UserOps/UpdateStatus.cshtml
@model DAL.Models.UsersTask

@{
    ViewData["Title"] = "UpdateStatus";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h1>UpdateStatus</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateStatus">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TaskId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" readonly />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" readonly />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" readonly />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
            
                <select asp-for="Status" class="form-control">
                    <option value="">-- Select Status --</option>
                    <option value="Assigned">Assigned</option>
                    <option value="Pending">Pending</option>
                    <option value="In Progress">In Progress</option>
                    <option value="Completed">Completed</option>
                </select>

                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskManagentHONB2/Views/UserOps/UserHomePage.cshtml
@{
    ViewData["Title"] = "UserHomePage";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h1>UserHomePage</h1>